name: Run build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run build
jobs:
  build:
    strategy:
        matrix:
          go: [1.18.0]
          os: [macos-latest, windows-latest, ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        
      - name: Check out code and run build
        uses: actions/checkout@v3
      - run: go build -ldflags="-s -w" ./...
