name: Run test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run test
jobs:
  test:
    strategy:
        matrix:
          go: [1.18.0]
          os: [macos-latest, windows-latest, ubuntu-latest]
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: on
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        
      - name: Check out code and run test
        uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - run: go env
