name: Run test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run golangci-lint
jobs:
  lint:
    strategy:
        matrix:
          go: [1.18.3]
          os: [macos-latest, windows-latest, ubuntu-latest]
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
        
      - name: Check out code and run test
        uses: actions/checkout@v3
        working-directory: src/main/go/cmd/hello
      - run: go test
